quarkus.banner.enabled=false

quarkus.rest-client.mexc-api.url=https://api.mexc.com/api/v3
quarkus.rest-client.mexc-api.scope=jakarta.inject.Singleton
quarkus.rest-client.headers.Accept=application/json
quarkus.rest-client.logging.scope=request-response

# Logging
quarkus.log.level=INFO
# quarkus.log.category."cz.amuradon".level=TRACE
quarkus.log.file.enable=true
quarkus.log.file.path=application.log

%test.quarkus.log.level=DEBUG

# 1. Aktivace Jib jako nástroje pro tvorbu image
quarkus.container-image.builder=jib

# 2. Definice cílového repozitáře (příklad pro Tokio)
quarkus.container-image.registry=asia-northeast1-docker.pkg.dev
quarkus.container-image.group=project-652d03b9-30e5-4ccd-b05/docker
quarkus.container-image.name=tv-bot
quarkus.container-image.tag=latest

# 3. Nastavení pro push
# Pokud chcete image jen sestavit lokálně, nastavte na false
quarkus.container-image.build=true
quarkus.container-image.push=true